[package]
name = "burp2code"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
clap = { version = "4.5.36", features = ["cargo"] }
colored = "3.0.0"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true